default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: smashub_dev

production:
  url: <%= ENV['DATABASE_URL'] %>
    

test:
  <<: *default
  database: smashub_test
