default: &default
  adapter: postgresql
  host: localhost
  user: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
    
  user: po2222stgres
  database: smashub_dev

test:
  <<: *default
  user: posdfsdfsd2222stgres
  database: smashub_test

production:
  url: <%= ENV['DATABASE_URL'] %>
